# Generated by Django 3.2.4 on 2021-06-24 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raisemodifyorder', '0002_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='adress',
            new_name='address',
        ),
    ]
