# Generated by Django 3.2.4 on 2021-06-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raisemodifyorder', '0005_auto_20210625_0900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
